---
apiVersion: v1
kind: Namespace
metadata:
  name: csns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deploy
  namespace: csns
  labels:
    app: code-server
    name: code-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
      name: code-server-po
  template:
    metadata:
      labels:
        app: code-server
        name: code-server-po
    spec:
      containers:
      - name: code-server-container
        image: linuxserver/code-server:4.92.2
        envFrom:
        - configMapRef:
            name: code-server-config   # Refers to the ConfigMap
        - secretRef:
            name: code-server-secret   # Refers to the Secret for passwords
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 200m
        volumeMounts:
          - mountPath: /config/workspace
            name: data-volume
        ports:
        - containerPort: 8443
      volumes: 
        - name: data-volume
          persistentVolumeClaim:
            claimName: workspace-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-svc
  namespace: csns
  labels:
    app: code-server
    name: code-server-svc
spec:
  type: ClusterIP
  selector:
    app: code-server
    name: code-server-po
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-ingress
  namespace: csns
  labels:
    app: code-server
    name: code-server-ing
spec:
  ingressClassName: nginx
  rules:
  - host: code.144.126.243.41.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend: 
            service: 
              name: code-server-svc
              port: 
                number: 8443