---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
  namespace: csns
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=          # 'password' base64 encoded
  SUDO_PASSWORD: cGFzc3dvcmQ=     # 'password' base64 encoded