---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-deploy
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels:
      app: bggapp
  template: 
    metadata:
      name: bggapp
      namespace: bggns
      labels:
        app: bggapp
    spec:
      containers:
      - name: bggapp
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: app-port
        livenessProbe:
          httpGet:
            path: /healthz
            port: app-port
---

apiVersion: v1
kind: Service
metadata: 
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector: 
    app: bggapp
  ports:
    - port: 80
      targetPort: app-port

---
apiVersion: v1
kind: Service
metadata: 
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg-database
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: 
    app: bgg-database
  ports:
    - port: 3306
      targetPort: 3306
