---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bgg-database
  namespace: bggns
  labels:
    app: bgg-database
    name: bgg-database
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bgg-database
  template: 
    metadata:
      namespace: bggns
      labels:
        app: bgg-database
        name: bgg-database
    spec:
      containers:
      - name: bgg-database
        image: stackupiss/bgg-database:v1
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata: 
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg-database
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: 
    app: bgg-database
  ports:
    - port: 3306
      targetPort: 3306