apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: minions
data:
  MINIO_ROOT_USER: "root"
  MINIO_DATA_DIR: "/data"
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: "minio-stateful-{0...3}.minio-hsvc.minions.svc.cluster.local/data"
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"